version: "3"
services:
        backend:
                build: ./wedding-backend
                ports: 
                        - "8000:8000"
                volumes:
                        - ./wedding-backend/src/:/root
                environment:
                        GOOS: "linux"
                        CGO_ENABLED: "1"

        frontend:
                build: ./wedding-frontend
                ports:
                        - "3000:3000"
                volumes:
                        - ./wedding-frontend/src:/node/src
                        - ./wedding-frontend/public:/node/public
        
        admin-frontend:
                build: ./wedding-admin-frontend
                ports:
                        - "3030:3000"
                environment:
                        - CI=true
                volumes:
                        - ./wedding-admin-frontend/src:/node/src
                        - ./wedding-admin-frontend/public:/node/public
